export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOG_OUT = 'auth/LOG_OUT';

export const LOGIN_FULFILLED = 'auth/LOGIN_FULFILLED';
export const LOGIN_PENDING = 'auth/LOGIN_PENDING';
export const LOGIN_REJECTED = 'auth/LOGIN_REJECTED';

export const REGISTRATION_CONFIRMED = 'auth/REGISTRATION_CONFIRMED';
export const REGISTRATION_FULFILLED = 'auth/REGISTRATION_FULFILLED';
export const REGISTRATION_PENDING = 'auth/REGISTRATION_PENDING';
export const REGISTRATION_REJECTED = 'auth/REGISTRATION_REJECTED';

export const GET_OFFERS_PENDING = 'offers/GET_OFFERS_PENDING';
export const GET_OFFERS_REJECTED = 'offers/GET_OFFERS_REJECTED';
export const GET_OFFERS_FULFILLED = 'offers/GET_OFFERS_FULFILLED';

export const POST_APPLICATION_PENDING = 'offers/POST_APPLICATION_PENDING';
export const POST_APPLICATION_REJECTED = 'offers/POST_APPLICATION_REJECTED';
export const POST_APPLICATION_FULFILLED = 'offers/POST_APPLICATION_FULFILLED';

export const GET_OPINIONS_PENDING = 'ratings/GET_OPINIONS_PENDING';
export const GET_OPINIONS_REJECTED = 'ratings/GET_OPINIONS_REJECTED';
export const GET_OPINIONS_FULFILLED = 'ratings/GET_OPINIONS_FULFILLED';

export const POST_OPINION_PENDING = 'ratings/POST_OPINION_PENDING';
export const POST_OPINION_REJECTED = 'ratings/POST_OPINION_REJECTED';
export const POST_OPINION_FULFILLED = 'ratings/POST_OPINION_FULFILLED';

export const GET_COMPANIES_PENDING = 'ratings/GET_COMPANIES_PENDING';
export const GET_COMPANIES_REJECTED = 'ratings/GET_COMPANIES_REJECTED';
export const GET_COMPANIES_FULFILLED = 'ratings/GET_COMPANIES_FULFILLED';

export default {
  CLEAR_ERRORS,
  LOG_OUT,

  LOGIN_FULFILLED,
  LOGIN_PENDING,
  LOGIN_REJECTED,

  REGISTRATION_CONFIRMED,
  REGISTRATION_FULFILLED,
  REGISTRATION_PENDING,
  REGISTRATION_REJECTED,

  GET_OFFERS_PENDING,
  GET_OFFERS_REJECTED,
  GET_OFFERS_FULFILLED,

  POST_APPLICATION_PENDING,
  POST_APPLICATION_REJECTED,
  POST_APPLICATION_FULFILLED,

  GET_OPINIONS_PENDING,
  GET_OPINIONS_REJECTED,
  GET_OPINIONS_FULFILLED,

  POST_OPINION_PENDING,
  POST_OPINION_REJECTED,
  POST_OPINION_FULFILLED,

  GET_COMPANIES_PENDING,
  GET_COMPANIES_REJECTED,
  GET_COMPANIES_FULFILLED,
};
