export const LOGIN_FULFILLED = 'auth/LOGIN_FULFILLED';
export const LOGIN_PENDING = 'auth/LOGIN_PENDING';
export const LOGIN_REJECTED = 'auth/LOGIN_REJECTED';
export const REGISTRATION_FULFILLED = 'auth/REGISTRATION_FULFILLED';
export const REGISTRATION_PENDING = 'auth/REGISTRATION_PENDING';
export const REGISTRATION_REJECTED = 'auth/REGISTRATION_REJECTED';
export const GET_OFFERS_PENDING = 'offers/GET_OFFERS_PENDING';
export const GET_OFFERS_REJECTED = 'offers/GET_OFFERS_REJECTED';
export const GET_OFFERS_FULFILLED = 'offers/GET_OFFERS_FULFILLED';

export default {
  LOGIN_FULFILLED,
  LOGIN_PENDING,
  LOGIN_REJECTED,
  REGISTRATION_FULFILLED,
  REGISTRATION_PENDING,
  REGISTRATION_REJECTED,
  GET_OFFERS_PENDING,
  GET_OFFERS_REJECTED,
  GET_OFFERS_FULFILLED,
};
